import React, { useEffect, useMemo, useState } from 'react';
import { ACHIEVEMENT_CATEGORIES, ACHIEVEMENT_LEVELS, deleteAchievementRemote, getAchievements, loadAchievementsFromSupabase, saveAchievements, uploadAchievementProof, upsertAchievement, type Achievement } from '../utils/achievementsStorage';
import { ProofUploadField, type ProofMetadata } from '../components/ui/ProofUploadField';

const emptyAchievement = (): Achievement => ({ id: '', title: '', category: 'Projects', organization: '', date: '', description: '', level: 'School', result: '', skillsGained: [], proofLink: '', proofFileName: null, proofFileType: null, proofFileSize: null, proofPreviewUrl: null, proofStorageUrl: null });

const proofMetadata = (achievement: Achievement): ProofMetadata => ({ proofFileName: achievement.proofFileName || null, proofFileType: achievement.proofFileType || null, proofFileSize: achievement.proofFileSize || null, proofPreviewUrl: achievement.proofPreviewUrl || null, proofStorageUrl: achievement.proofStorageUrl || null });

export const AchievementsPage: React.FC = () => {
  const [achievements, setAchievements] = useState<Achievement[]>(getAchievements);
  const [filter, setFilter] = useState('all');
  const [editing, setEditing] = useState<Achievement | null>(null);
  const [viewing, setViewing] = useState<Achievement | null>(null);
  const [proofFile, setProofFile] = useState<File | null>(null);
  useEffect(() => { loadAchievementsFromSupabase().then(setAchievements).catch((error) => window.alert(error instanceof Error ? error.message : 'Unable to load achievements.')); }, []);

  const visible = useMemo(() => achievements
    .filter((achievement) => filter === 'all' || achievement.category === filter)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()), [achievements, filter]);

  const persist = (next: Achievement[]) => { setAchievements(next); saveAchievements(next); };
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!editing) return;
    let record = { ...editing, id: editing.id || (crypto.randomUUID?.() || `${Date.now()}`) };
    try { if (proofFile) { const uploaded = await uploadAchievementProof(proofFile); record = { ...record, proofStorageUrl: uploaded.path, proofPreviewUrl: uploaded.signedUrl }; } await upsertAchievement(record); } catch (error) { window.alert(error instanceof Error ? error.message : 'Unable to save achievement.'); return; }
    persist(editing.id ? achievements.map((item) => item.id === editing.id ? record : item) : [...achievements, record]);
    setEditing(null);
  };
  const remove = async (achievement: Achievement) => {
    if (window.confirm(`Delete “${achievement.title}”? This cannot be undone.`)) { try { await deleteAchievementRemote(achievement.id); persist(achievements.filter((item) => item.id !== achievement.id)); } catch (error) { window.alert(error instanceof Error ? error.message : 'Unable to delete achievement.'); } }
  };

  return <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50/30 px-4 py-8 sm:px-6 lg:px-8">
    <div className="mx-auto max-w-6xl">
      <div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Build your profile</p><h1 className="mt-2 text-4xl font-bold text-gray-900">Achievements</h1><p className="mt-2 text-gray-600">Keep projects, awards, leadership, and experiences in one place.</p></div><button onClick={() => setEditing(emptyAchievement())} className="rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 px-6 py-3 font-semibold text-white shadow-lg hover:shadow-xl">Add Achievement</button></div>
      <div className="mb-8 rounded-2xl border border-gray-100 bg-white p-5 shadow-md"><div className="flex flex-wrap gap-2"><button onClick={() => setFilter('all')} className={`rounded-full px-4 py-2 text-sm font-semibold ${filter === 'all' ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-700'}`}>All</button>{ACHIEVEMENT_CATEGORIES.map((category) => <button key={category} onClick={() => setFilter(category)} className={`rounded-full px-4 py-2 text-sm font-semibold ${filter === category ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-700'}`}>{category}</button>)}</div></div>
      {visible.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{visible.map((achievement) => <article key={achievement.id} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-lg"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-purple-100 px-3 py-1 text-xs font-bold text-purple-700">{achievement.category}</span><span className="text-xs font-semibold text-gray-500">{achievement.level}</span></div><h2 className="mt-4 text-xl font-bold text-gray-900">{achievement.title}</h2><p className="mt-1 text-sm text-gray-500">{achievement.organization || 'Independent'} · {achievement.date || 'Date not set'}</p><p className="mt-4 line-clamp-3 text-sm text-gray-700">{achievement.description || achievement.result || 'No description added.'}</p><div className="mt-6 flex flex-wrap gap-2"><button onClick={() => setViewing(achievement)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">View Details</button><button onClick={() => setEditing({ ...achievement })} className="rounded-lg bg-gray-100 px-4 py-2 text-sm font-semibold text-gray-700">Edit</button><button onClick={() => remove(achievement)} className="rounded-lg px-3 py-2 text-sm font-semibold text-red-600 hover:bg-red-50">Delete</button></div></article>)}</div> : <div className="rounded-3xl border-2 border-dashed border-gray-200 bg-white py-20 text-center"><div className="text-6xl">🏆</div><h2 className="mt-5 text-2xl font-bold text-gray-900">No achievements yet</h2><p className="mx-auto mt-2 max-w-md text-gray-600">Add your first project, certificate, competition, or experience to strengthen your recommendations.</p><button onClick={() => setEditing(emptyAchievement())} className="mt-6 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 px-6 py-3 font-semibold text-white">Add Your First Achievement</button></div>}
    </div>

    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold text-gray-900">{editing.id ? 'Edit Achievement' : 'Add Achievement'}</h2><button type="button" onClick={() => setEditing(null)} className="text-2xl text-gray-500">×</button></div><div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Title</span><input required value={editing.title} onChange={(e) => setEditing({...editing,title:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label><span className="mb-2 block text-sm font-semibold">Category</span><select value={editing.category} onChange={(e) => setEditing({...editing,category:e.target.value as Achievement['category']})} className="w-full rounded-xl border border-gray-300 px-4 py-3">{ACHIEVEMENT_CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select></label>
      <label><span className="mb-2 block text-sm font-semibold">Level</span><select value={editing.level} onChange={(e) => setEditing({...editing,level:e.target.value as Achievement['level']})} className="w-full rounded-xl border border-gray-300 px-4 py-3">{ACHIEVEMENT_LEVELS.map((item)=><option key={item}>{item}</option>)}</select></label>
      <label><span className="mb-2 block text-sm font-semibold">Organization</span><input value={editing.organization} onChange={(e) => setEditing({...editing,organization:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label><span className="mb-2 block text-sm font-semibold">Date</span><input type="date" value={editing.date} onChange={(e) => setEditing({...editing,date:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Description</span><textarea rows={3} value={editing.description} onChange={(e) => setEditing({...editing,description:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label><span className="mb-2 block text-sm font-semibold">Result or Award</span><input value={editing.result} onChange={(e) => setEditing({...editing,result:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label><span className="mb-2 block text-sm font-semibold">Skills Gained</span><input value={editing.skillsGained.join(', ')} onChange={(e) => setEditing({...editing,skillsGained:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} placeholder="Coding, teamwork" className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Certificate or Proof Link (optional)</span><input type="url" value={editing.proofLink || ''} onChange={(e) => setEditing({...editing,proofLink:e.target.value})} className="w-full rounded-xl border border-gray-300 px-4 py-3" /></label>
      <div className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Proof File (optional)</span><ProofUploadField value={proofMetadata(editing)} onChange={(metadata,file) => { setEditing({ ...editing, ...metadata }); setProofFile(file); }} /></div>
    </div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="rounded-xl px-5 py-3 font-semibold text-gray-600">Cancel</button><button className="rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 px-6 py-3 font-semibold text-white">Save Achievement</button></div></form></div>}
    {viewing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setViewing(null)}><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-7 shadow-2xl" onClick={(e)=>e.stopPropagation()}><div className="flex justify-between gap-4"><div><span className="text-sm font-semibold text-purple-700">{viewing.category} · {viewing.level}</span><h2 className="mt-2 text-3xl font-bold text-gray-900">{viewing.title}</h2></div><button onClick={()=>setViewing(null)} className="text-2xl text-gray-500">×</button></div><div className="mt-6 space-y-4 text-gray-700"><p><strong>Organization:</strong> {viewing.organization || 'Independent'}</p><p><strong>Date:</strong> {viewing.date || 'Not set'}</p><p><strong>Description:</strong> {viewing.description || 'Not provided'}</p><p><strong>Result:</strong> {viewing.result || 'Not provided'}</p><p><strong>Skills:</strong> {viewing.skillsGained.join(', ') || 'Not provided'}</p>{viewing.proofFileName ? <div className="rounded-xl border border-gray-200 bg-gray-50 p-4">{viewing.proofFileType?.startsWith('image/') && viewing.proofPreviewUrl ? <img src={viewing.proofPreviewUrl} alt={`${viewing.title} proof`} className="max-h-64 w-full rounded-lg object-contain" /> : <div className="flex items-center gap-3"><span className="text-4xl">📄</span><div><p className="font-semibold text-gray-900">{viewing.proofFileName}</p><p className="text-sm text-gray-500">{viewing.proofFileType === 'application/pdf' ? 'PDF document' : 'Proof file'}</p></div></div>}<div className="mt-4">{viewing.proofPreviewUrl ? <a href={viewing.proofPreviewUrl} target="_blank" rel="noreferrer" className="inline-flex rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">View Proof</a> : <p className="text-sm text-gray-500">Preview expired. Replace the file to view it again; only metadata is stored until cloud storage is connected.</p>}</div></div> : <p className="rounded-xl bg-gray-50 p-4 text-sm text-gray-500">No proof uploaded</p>}{viewing.proofLink && <a href={viewing.proofLink} target="_blank" rel="noreferrer" className="inline-flex font-semibold text-blue-700">View certificate or proof link ↗</a>}</div></div></div>}
  </div>;
};
